### ISSUE TITLE
付録 A-2 エスケープシーケンス表 カーソルの表示

### ISSUE THREAD

**Issue by makicamel** [mame/trance-book#1]
とても面白い本をありがとうございます。楽しませて頂いています。

付録 A-2 エスケープシーケンス表にて `\x1b[?25j` が「カーソルを表示する」と記載されているのですが、 `\x1b[?25h` ではないでしょうか?

**Comment by mame** [comment]
おお、ほんとですね。ありがとうございます。https://mame.github.io/trance-book/errata.html に追加しておきましたー。
